# Generated by Django 4.2.16 on 2024-11-10 08:20

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the award (e.g., Best Performer, Most Improved).', max_length=100)),
                ('date_created', models.DateField(auto_now_add=True, help_text='Date the award was added.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text="Date the award's record was last updated.")),
            ],
        ),
        migrations.CreateModel(
            name='ClubsOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the club or organization (e.g., Debate Club).', max_length=100)),
                ('date_created', models.DateField(auto_now_add=True, help_text='Date the club or organization was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text="Date the club or organization's record was last updated.")),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Educational level (e.g., Grade 1, PP1).', max_length=50)),
                ('date_created', models.DateField(auto_now_add=True, help_text='Date the grade was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text="Date the grade's record was last updated.")),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='identity.customuser')),
                ('national_id_number', models.CharField(blank=True, help_text='National ID number of the guardian.', max_length=50, null=True, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number for identifying and contacting the guardian.', max_length=128, region=None, unique=True)),
                ('date_created', models.DateField(auto_now_add=True, help_text='Date the guardian was added to the system.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text="Date the guardian's record was last updated.")),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
            },
            bases=('identity.customuser',),
        ),
        migrations.CreateModel(
            name='HomeworkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sport (e.g., Soccer, Basketball).', max_length=100)),
                ('date_created', models.DateField(auto_now_add=True, help_text='Date the sport was added.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text="Date the sport's record was last updated.")),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the academic subject (e.g., Math, Science).', max_length=100)),
                ('date_created', models.DateField(auto_now_add=True, help_text='Date the subject was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text="Date the subject's record was last updated.")),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='identity.customuser')),
                ('student_identity', models.CharField(help_text='Unique student identifier in the school (e.g., Admission number).', max_length=255)),
                ('enrollment_date', models.DateField(help_text='Date the student was admitted into the school.')),
                ('emergency_contact_name', models.CharField(help_text="Name of the student's emergency contact.", max_length=255)),
                ('emergency_contact_relationship', models.CharField(choices=[('parent or guardian', 'Parent or Guardian'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandparent', 'Grandparent'), ('cousin', 'Cousin'), ('trusted family friend', 'Trusted Family Friend')], help_text='Relationship between the emergency contact and the student.', max_length=100)),
                ('emergency_contact_phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number of the emergency contact, preferably someone who can respond quickly in emergencies.', max_length=128, region=None)),
                ('date_added_to_system', models.DateField(auto_now_add=True, help_text='Date the student was added to the system.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text="Date the student's record was last updated.")),
                ('awards', models.ManyToManyField(blank=True, help_text='Awards the student has received.', to='studentmanagement.award')),
                ('clubs', models.ManyToManyField(blank=True, help_text='Clubs the student is a member of.', to='studentmanagement.clubsorganization')),
                ('grade', models.ForeignKey(help_text='Current grade level of the student.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentmanagement.grade')),
                ('parentguardian', models.ForeignKey(help_text='Parent or guardian associated with the student.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentmanagement.guardian')),
                ('school', models.ForeignKey(help_text='School where the student is enrolled.', on_delete=django.db.models.deletion.CASCADE, to='identity.school')),
                ('sports', models.ManyToManyField(blank=True, help_text='Sports the student participates in.', to='studentmanagement.sport')),
                ('subjects', models.ManyToManyField(blank=True, help_text='Subjects the student is taking.', to='studentmanagement.subject')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('identity.customuser',),
        ),
    ]
