# Generated by Django 4.2.16 on 2024-11-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional', max_length=254, null=True),
        ),
    ]
