# Generated by Django 4.2.16 on 2024-11-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='national_id_or_birth_cert_name',
            field=models.CharField(help_text='For student provide the full name on the birth certificate. For an administrator,teacher,staff,parent etc provide the name on th ID card', max_length=100),
        ),
    ]
