# Generated by Django 4.2.16 on 2024-11-05 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='This is the rank an administrator holds, e.g., principal, deputy principal, headteacher, etc.', max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='identity.customuser')),
                ('date_of_joining', models.DateField(blank=True, help_text='Date the administrator joined the school', null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('rank', models.ForeignKey(help_text="Administrator's rank within the school", null=True, on_delete=django.db.models.deletion.SET_NULL, to='schooladministration.administratorrank')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.school')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('identity.customuser',),
        ),
    ]
