# Generated by Django 4.2.16 on 2024-11-10 08:20

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='This is the rank an administrator holds, e.g., principal, deputy principal, headteacher, etc.', max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='identity.customuser')),
                ('professional_identity', models.CharField(blank=True, help_text='Professional identifier assigned by an organization, e.g., TSC number for teachers.', max_length=255, null=True)),
                ('national_id_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None, unique=True)),
                ('date_of_joining', models.DateField(blank=True, help_text='Date the administrator joined the school.', null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('ranks', models.ManyToManyField(help_text="Administrator's ranks within the school", related_name='administrators', to='schooladministration.administratorrank')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.school')),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
            },
            bases=('identity.customuser',),
        ),
    ]
