# Generated by Django 4.2.16 on 2024-11-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladministration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': 'Administrator', 'verbose_name_plural': 'Administrators'},
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='rank',
        ),
        migrations.AddField(
            model_name='administrator',
            name='ranks',
            field=models.ManyToManyField(help_text="Administrator's ranks within the school", related_name='administrators', to='schooladministration.administratorrank'),
        ),
    ]
