# Generated by Django 4.2.16 on 2024-11-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladministration', '0002_alter_administrator_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='professional_identity',
            field=models.CharField(blank=True, help_text='Professional identifier assigned by an organization, e.g., TSC number for teachers.', max_length=255, null=True),
        ),
    ]
